# GitHub Actions workflow file for building a Node.js project

name: Amadeus frontend 

on:
  push:
      branches: ["main"]
  pull_request:
      branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Setup node 
      uses: actions/setup-node@v4
      with:    
        node-version: 24.1.0

    - name: Restore dependencies  
      run: npm i
    - name: Build project
      run: npm run build